### ISSUE TITLE
Understand pricing of cloud speech-to-text offers

### ISSUE THREAD

**Issue by jacek-** [iLOSTA/The-Project#6]
Register for the API asap.

**Comment by iLOSTA** [comment]
Successfully registered for Google, Amazon and Azure services. The pricing is detailed below.

GOOGLE: Free up to 60 minutes. After that $0.004/15 seconds. That is, around $1/60 minutes.
It doesn't mention whether it resets monthly.

AMAZON: Free 60 minutes per month. After that, around $1.44/60 minutes.

AZURE: Free 5 hours per month.
